services:
  bumper:
    build: .                              # location of the Dockerfile
    container_name: discord-auto-bumper
    user: ${UID:-1000}:${GID:-1000}
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: ${RESTART:-no}
    environment:
      - PYTHONUNBUFFERED=1

  config:
    build: .
    container_name: discord-bumper-config
    user: ${UID:-1000}:${GID:-1000}
    env_file: .env
    profiles:
      # makes the docker-compose up not start this service
      - setup
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: python main.py --config
